# Site description
title: Natalia Calixto
url: NataliaCalixto.com
description: "Work of Natalia Calixto"
image: "http://hexecontahedron.com/static/img/hexe-small.png" # TODO
keywords: "Architecture, Photography"
author: Alberto Barradas
credits: 'Handcrafted by <a href="http://github.com/abcsds">Alberto Barradas</a>'
sections:
  - name: Architecture
    link: arch.html
  - name: Photography
    link: photo.html

# Social
name: Natalia Calixto
email: nat.ccs14@gmail.com
# twitter_username: ""
# github_username:  ""
# googlep_username: ""
# personal_website: "http://NataliaCalixto.com"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed
static_folder: "static"
exclude:
- README.md
- CNAME
