# Site settings
title: Natalia Calixto
url: https://example.github.io
description: "Portafolio de Trabajo de Natalia Calixto"
skills: "Arquitecta - Fot&oacute;grafa - Activista"
meta_author: Alberto Barradas

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: abcsds

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C43F1D #076519
  primary-rgb: "230, 136, 84" #"rgb(24,288,156)"
  secondary: 4B3C08 #233140
  secondary-dark: 857130 #2c3e50

# Footer settings
footer:
  copyright: Natalia Calixto
  location: Ubicaci&oacute;n
  social: Social
  credits: Cr&eacute;ditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/nat.ccs.9
  - title: envelope
    url: mailto:nat.ccs14@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Le&oacute;n M&eacute;xico

# Credits content
credits: 'Moldeado desde <a href="http://startbootstrap.com">c&oacute;digo abierto</a> por <a href="http://github.com/abcsds">Alberto Barradas</a>'

# Build settings
markdown: kramdown
permalink: pretty
